steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/subba-personal-project/hello:v1", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/subba-personal-project/hello:v1"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-resource-file
  - --image=gcr.io/subba-personal-project/hello:v1
  - -- deployment=/hello:v1
  - --location=us-central1-c
  - --cluster=cluster-1
options:
  logging: CLOUD_LOGGING_ONLY
  